name: "unittest"
version: "0.2.10"
usage: "Please see https://github.com/heyhabito/helm-unittest for usage"
description: "Unit testing for Helm charts"
command: "$HELM_PLUGIN_DIR/untt"
useTunnel: false
hooks:
  install: "cd $HELM_PLUGIN_DIR; bash ./install_plugin.sh"
  update: "cd $HELM_PLUGIN_DIR; bash ./install_plugin.sh"
